version: "3.9"
services:
  client:
    build: ./client
    ports:
      - "1234:1234"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
  server:
    build: ./server
    ports: 
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./server:/usr/src/app
  prisma-studio:
    build: ./server
    ports: 
      - "5555:5555"
    depends_on:
      - postgres
    volumes:
      - ./server:/usr/src/app
  postgres:
    image: postgres
    ports:
      - "8002:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
